# Copyright 2018-2019 Peter K. G. Williams and collaborators
# Licensed under the GPL version 3

language: rust

cache: cargo

matrix:
  include:
    - os: linux
      sudo: required
      dist: xenial
      rust: stable
    - os: linux
      sudo: required
      dist: xenial
      rust: beta
    - os: linux
      sudo: required
      dist: xenial
      rust: nightly
  allow_failures:
    - rust: nightly

# Don't CI branches besides master. PR's still get built! This prevents PRs
# being built twice in the standard workflow.
branches:
  only:
    - master

addons:
  apt:
    packages:
      - libgsl-dev

script:
  - |
    cargo build --verbose &&
    cargo test
